import Foundation

/// Complete ingredient database matching AminoFeed structure
/// Includes all nutrients, SID amino acids, and WPSA energy calculations
struct IngredientDatabase {

    /// SID digestibility coefficients by ingredient and amino acid
    static let sidDigestibility: [String: [String: Double]] = [
        "Corn": [
            "lysine": 0.91, "methionine": 0.95, "metCys": 0.92,
            "threonine": 0.89, "tryptophan": 0.83, "arginine": 0.89,
            "isoleucine": 0.98, "leucine": 0.93, "valine": 0.95
        ],
        "Wheat": [
            "lysine": 0.87, "methionine": 0.93, "metCys": 0.90,
            "threonine": 0.85, "tryptophan": 0.86, "arginine": 0.91,
            "isoleucine": 0.89, "leucine": 0.91, "valine": 0.89
        ],
        "Barley": [
            "lysine": 0.84, "methionine": 0.90, "metCys": 0.87,
            "threonine": 0.82, "tryptophan": 0.83, "arginine": 0.88,
            "isoleucine": 0.86, "leucine": 0.88, "valine": 0.86
        ],
        "Oats": [
            "lysine": 0.85, "methionine": 0.91, "metCys": 0.88,
            "threonine": 0.83, "tryptophan": 0.84, "arginine": 0.89,
            "isoleucine": 0.87, "leucine": 0.89, "valine": 0.87
        ],
        "Rye": [
            "lysine": 0.83, "methionine": 0.89, "metCys": 0.86,
            "threonine": 0.81, "tryptophan": 0.82, "arginine": 0.87,
            "isoleucine": 0.85, "leucine": 0.87, "valine": 0.85
        ],
        "Rice": [
            "lysine": 0.88, "methionine": 0.92, "metCys": 0.89,
            "threonine": 0.86, "tryptophan": 0.85, "arginine": 0.90,
            "isoleucine": 0.88, "leucine": 0.90, "valine": 0.88
        ],
        "Sorghum, Low Tannin": [
            "lysine": 0.82, "methionine": 0.91, "metCys": 0.88,
            "threonine": 0.84, "tryptophan": 0.81, "arginine": 0.87,
            "isoleucine": 0.89, "leucine": 0.91, "valine": 0.89
        ],
        "Sorghum, High Tannin": [
            "lysine": 0.75, "methionine": 0.85, "metCys": 0.82,
            "threonine": 0.78, "tryptophan": 0.75, "arginine": 0.81,
            "isoleucine": 0.83, "leucine": 0.85, "valine": 0.83
        ],
        "Soybean Meal": [
            "lysine": 0.91, "methionine": 0.92, "metCys": 0.88,
            "threonine": 0.87, "tryptophan": 0.87, "arginine": 0.93,
            "isoleucine": 0.89, "leucine": 0.90, "valine": 0.88
        ],
        "Sunflower Meal, partially dehulled": [
            "lysine": 0.85, "methionine": 0.92, "metCys": 0.86,
            "threonine": 0.84, "tryptophan": 0.86, "arginine": 0.91,
            "isoleucine": 0.87, "leucine": 0.88, "valine": 0.86
        ],
        "Canola Meal": [
            "lysine": 0.83, "methionine": 0.89, "metCys": 0.84,
            "threonine": 0.80, "tryptophan": 0.82, "arginine": 0.87,
            "isoleucine": 0.83, "leucine": 0.85, "valine": 0.82
        ],
        "Corn Gluten Meal": [
            "lysine": 0.88, "methionine": 0.96, "metCys": 0.93,
            "threonine": 0.91, "tryptophan": 0.87, "arginine": 0.93,
            "isoleucine": 0.94, "leucine": 0.97, "valine": 0.94
        ],
        "Fish Meal 65%": [
            "lysine": 0.93, "methionine": 0.93, "metCys": 0.89,
            "threonine": 0.90, "tryptophan": 0.89, "arginine": 0.92,
            "isoleucine": 0.91, "leucine": 0.92, "valine": 0.90
        ],
        "Meat and Bone Meal": [
            "lysine": 0.82, "methionine": 0.85, "metCys": 0.78,
            "threonine": 0.79, "tryptophan": 0.77, "arginine": 0.84,
            "isoleucine": 0.80, "leucine": 0.83, "valine": 0.79
        ],
        "Poultry By-Product Meal": [
            "lysine": 0.87, "methionine": 0.89, "metCys": 0.83,
            "threonine": 0.84, "tryptophan": 0.82, "arginine": 0.88,
            "isoleucine": 0.85, "leucine": 0.87, "valine": 0.84
        ],
        "DL-Methionine": [
            "lysine": 1.00, "methionine": 1.00, "metCys": 0.99,
            "threonine": 1.00, "tryptophan": 1.00, "arginine": 1.00,
            "isoleucine": 1.00, "leucine": 1.00, "valine": 1.00
        ],
        "L-Lysine-HCl": [
            "lysine": 1.00, "methionine": 1.00, "metCys": 1.00,
            "threonine": 1.00, "tryptophan": 1.00, "arginine": 1.00,
            "isoleucine": 1.00, "leucine": 1.00, "valine": 1.00
        ],
        "L-Threonine": [
            "lysine": 1.00, "methionine": 1.00, "metCys": 1.00,
            "threonine": 1.00, "tryptophan": 1.00, "arginine": 1.00,
            "isoleucine": 1.00, "leucine": 1.00, "valine": 1.00
        ]
    ]

    /// WPSA energy calculation coefficients (kJ/g converted to kcal/kg factor)
    static let wpsaCoefficients = WPSACoefficients(
        crudeProtein: 15.15,  // kJ/g
        etherExtract: 35.75,   // kJ/g
        nfe: 15.59,            // kJ/g
        crudeFiber: 0.0,       // Usually excluded or minimal
        ash: 0.0,              // No energy
        starch: 17.0,          // kJ/g
        sugar: 17.0,           // kJ/g
        conversionFactor: 0.238846  // kJ to kcal
    )

    /// Complete ingredient library matching AminoFeed structure
    static let completeLibrary: [IngredientData] = [
        // ==================== GRAINS ====================
        IngredientData(
            name: "Corn",
            group: .grain,
            dryMatter: 88.0,
            crudeProtein: 7.42,
            etherExtract: 3.50,
            crudeFiber: 2.10,
            ash: 1.20,
            starch: 62.0,
            sugar: 1.80,
            totalLysine: 0.24,
            totalMethionine: 0.18,
            totalMetCys: 0.35,
            totalThreonine: 0.28,
            totalTryptophan: 0.06,
            totalArginine: 0.37,
            totalIsoleucine: 0.28,
            totalLeucine: 0.96,
            totalValine: 0.38,
            calcium: 0.01,
            totalPhosphorus: 0.28,
            availablePhosphorus: 0.08,
            sodium: 0.02,
            potassium: 0.30,
            chloride: 0.05,
            minPercent: 0,
            maxPercent: 70,
            pricePerKg: 45000
        ),

        IngredientData(
            name: "Wheat",
            group: .grain,
            dryMatter: 88.0,
            crudeProtein: 11.50,
            etherExtract: 1.70,
            crudeFiber: 2.80,
            ash: 1.60,
            starch: 60.0,
            sugar: 2.50,
            totalLysine: 0.34,
            totalMethionine: 0.20,
            totalMetCys: 0.42,
            totalThreonine: 0.33,
            totalTryptophan: 0.14,
            totalArginine: 0.52,
            totalIsoleucine: 0.39,
            totalLeucine: 0.75,
            totalValine: 0.48,
            calcium: 0.05,
            totalPhosphorus: 0.32,
            availablePhosphorus: 0.10,
            sodium: 0.01,
            potassium: 0.38,
            chloride: 0.07,
            minPercent: 0,
            maxPercent: 50,
            pricePerKg: 15500
        ),

        IngredientData(
            name: "Barley",
            group: .grain,
            dryMatter: 88.0,
            crudeProtein: 10.80,
            etherExtract: 2.10,
            crudeFiber: 5.00,
            ash: 2.30,
            starch: 52.0,
            sugar: 2.00,
            totalLysine: 0.38,
            totalMethionine: 0.18,
            totalMetCys: 0.40,
            totalThreonine: 0.35,
            totalTryptophan: 0.13,
            totalArginine: 0.49,
            totalIsoleucine: 0.37,
            totalLeucine: 0.70,
            totalValine: 0.52,
            calcium: 0.05,
            totalPhosphorus: 0.34,
            availablePhosphorus: 0.12,
            sodium: 0.02,
            potassium: 0.42,
            chloride: 0.12,
            minPercent: 0,
            maxPercent: 40,
            pricePerKg: 10000
        ),

        IngredientData(
            name: "Oats",
            group: .grain,
            dryMatter: 89.0,
            crudeProtein: 11.30,
            etherExtract: 4.80,
            crudeFiber: 10.50,
            ash: 3.00,
            starch: 40.0,
            sugar: 1.50,
            totalLysine: 0.42,
            totalMethionine: 0.18,
            totalMetCys: 0.46,
            totalThreonine: 0.36,
            totalTryptophan: 0.14,
            totalArginine: 0.70,
            totalIsoleucine: 0.42,
            totalLeucine: 0.78,
            totalValine: 0.56,
            calcium: 0.08,
            totalPhosphorus: 0.34,
            availablePhosphorus: 0.10,
            sodium: 0.02,
            potassium: 0.42,
            chloride: 0.08,
            minPercent: 0,
            maxPercent: 20,
            pricePerKg: 100
        ),

        IngredientData(
            name: "Rye",
            group: .grain,
            dryMatter: 88.0,
            crudeProtein: 10.50,
            etherExtract: 1.50,
            crudeFiber: 2.50,
            ash: 1.80,
            starch: 55.0,
            sugar: 4.50,
            totalLysine: 0.40,
            totalMethionine: 0.17,
            totalMetCys: 0.38,
            totalThreonine: 0.32,
            totalTryptophan: 0.11,
            totalArginine: 0.50,
            totalIsoleucine: 0.36,
            totalLeucine: 0.65,
            totalValine: 0.48,
            calcium: 0.06,
            totalPhosphorus: 0.32,
            availablePhosphorus: 0.10,
            sodium: 0.01,
            potassium: 0.48,
            chloride: 0.06,
            minPercent: 0,
            maxPercent: 15,
            pricePerKg: 100
        ),

        IngredientData(
            name: "Rice",
            group: .grain,
            dryMatter: 88.0,
            crudeProtein: 7.50,
            etherExtract: 1.80,
            crudeFiber: 0.80,
            ash: 0.60,
            starch: 72.0,
            sugar: 0.50,
            totalLysine: 0.28,
            totalMethionine: 0.20,
            totalMetCys: 0.38,
            totalThreonine: 0.28,
            totalTryptophan: 0.09,
            totalArginine: 0.58,
            totalIsoleucine: 0.34,
            totalLeucine: 0.64,
            totalValine: 0.46,
            calcium: 0.03,
            totalPhosphorus: 0.14,
            availablePhosphorus: 0.05,
            sodium: 0.01,
            potassium: 0.12,
            chloride: 0.02,
            minPercent: 0,
            maxPercent: 30,
            pricePerKg: 100
        ),

        IngredientData(
            name: "Soybean full fat, Extruded",
            group: .grain,
            dryMatter: 90.0,
            crudeProtein: 36.0,
            etherExtract: 18.0,
            crudeFiber: 5.50,
            ash: 5.00,
            starch: 7.00,
            sugar: 7.50,
            totalLysine: 2.35,
            totalMethionine: 0.52,
            totalMetCys: 1.08,
            totalThreonine: 1.45,
            totalTryptophan: 0.52,
            totalArginine: 2.70,
            totalIsoleucine: 1.70,
            totalLeucine: 2.85,
            totalValine: 1.78,
            calcium: 0.28,
            totalPhosphorus: 0.58,
            availablePhosphorus: 0.20,
            sodium: 0.01,
            potassium: 1.90,
            chloride: 0.04,
            minPercent: 0,
            maxPercent: 25,
            pricePerKg: 100
        ),

        IngredientData(
            name: "Soybean full fat, Roasted",
            group: .grain,
            dryMatter: 90.0,
            crudeProtein: 37.0,
            etherExtract: 18.5,
            crudeFiber: 5.00,
            ash: 4.80,
            starch: 6.50,
            sugar: 7.00,
            totalLysine: 2.40,
            totalMethionine: 0.54,
            totalMetCys: 1.10,
            totalThreonine: 1.48,
            totalTryptophan: 0.54,
            totalArginine: 2.75,
            totalIsoleucine: 1.72,
            totalLeucine: 2.90,
            totalValine: 1.80,
            calcium: 0.26,
            totalPhosphorus: 0.56,
            availablePhosphorus: 0.18,
            sodium: 0.01,
            potassium: 1.85,
            chloride: 0.04,
            minPercent: 0,
            maxPercent: 25,
            pricePerKg: 100
        ),

        IngredientData(
            name: "Linseeds",
            group: .grain,
            dryMatter: 91.0,
            crudeProtein: 22.0,
            etherExtract: 34.0,
            crudeFiber: 7.50,
            ash: 4.00,
            starch: 1.50,
            sugar: 3.50,
            totalLysine: 0.88,
            totalMethionine: 0.45,
            totalMetCys: 0.85,
            totalThreonine: 0.80,
            totalTryptophan: 0.35,
            totalArginine: 2.00,
            totalIsoleucine: 0.98,
            totalLeucine: 1.30,
            totalValine: 1.10,
            calcium: 0.24,
            totalPhosphorus: 0.62,
            availablePhosphorus: 0.15,
            sodium: 0.03,
            potassium: 0.85,
            chloride: 0.05,
            minPercent: 0,
            maxPercent: 10,
            pricePerKg: 100
        ),

        IngredientData(
            name: "Peas",
            group: .grain,
            dryMatter: 88.0,
            crudeProtein: 22.0,
            etherExtract: 1.20,
            crudeFiber: 6.00,
            ash: 2.80,
            starch: 45.0,
            sugar: 5.50,
            totalLysine: 1.58,
            totalMethionine: 0.22,
            totalMetCys: 0.52,
            totalThreonine: 0.82,
            totalTryptophan: 0.20,
            totalArginine: 1.90,
            totalIsoleucine: 0.92,
            totalLeucine: 1.55,
            totalValine: 1.00,
            calcium: 0.08,
            totalPhosphorus: 0.40,
            availablePhosphorus: 0.12,
            sodium: 0.02,
            potassium: 1.00,
            chloride: 0.05,
            minPercent: 0,
            maxPercent: 20,
            pricePerKg: 100
        ),

        IngredientData(
            name: "Sorghum, Low Tannin",
            group: .grain,
            dryMatter: 88.0,
            crudeProtein: 9.00,
            etherExtract: 2.80,
            crudeFiber: 2.50,
            ash: 1.50,
            starch: 65.0,
            sugar: 1.50,
            totalLysine: 0.22,
            totalMethionine: 0.17,
            totalMetCys: 0.32,
            totalThreonine: 0.30,
            totalTryptophan: 0.10,
            totalArginine: 0.35,
            totalIsoleucine: 0.38,
            totalLeucine: 1.20,
            totalValine: 0.48,
            calcium: 0.03,
            totalPhosphorus: 0.28,
            availablePhosphorus: 0.08,
            sodium: 0.01,
            potassium: 0.32,
            chloride: 0.05,
            minPercent: 0,
            maxPercent: 50,
            pricePerKg: 100
        ),

        IngredientData(
            name: "Sorghum, High Tannin",
            group: .grain,
            dryMatter: 88.0,
            crudeProtein: 9.50,
            etherExtract: 2.90,
            crudeFiber: 2.80,
            ash: 1.60,
            starch: 63.0,
            sugar: 1.80,
            totalLysine: 0.23,
            totalMethionine: 0.17,
            totalMetCys: 0.33,
            totalThreonine: 0.31,
            totalTryptophan: 0.10,
            totalArginine: 0.36,
            totalIsoleucine: 0.39,
            totalLeucine: 1.22,
            totalValine: 0.49,
            calcium: 0.03,
            totalPhosphorus: 0.29,
            availablePhosphorus: 0.08,
            sodium: 0.01,
            potassium: 0.33,
            chloride: 0.05,
            minPercent: 0,
            maxPercent: 30,
            pricePerKg: 100
        ),

        IngredientData(
            name: "Millet, Pearl",
            group: .grain,
            dryMatter: 89.0,
            crudeProtein: 11.0,
            etherExtract: 4.20,
            crudeFiber: 2.30,
            ash: 1.80,
            starch: 60.0,
            sugar: 1.50,
            totalLysine: 0.21,
            totalMethionine: 0.22,
            totalMetCys: 0.42,
            totalThreonine: 0.35,
            totalTryptophan: 0.12,
            totalArginine: 0.38,
            totalIsoleucine: 0.42,
            totalLeucine: 1.15,
            totalValine: 0.52,
            calcium: 0.03,
            totalPhosphorus: 0.30,
            availablePhosphorus: 0.09,
            sodium: 0.01,
            potassium: 0.35,
            chloride: 0.05,
            minPercent: 0,
            maxPercent: 30,
            pricePerKg: 100
        ),

        IngredientData(
            name: "Triticale",
            group: .grain,
            dryMatter: 88.0,
            crudeProtein: 11.80,
            etherExtract: 1.60,
            crudeFiber: 2.60,
            ash: 1.90,
            starch: 58.0,
            sugar: 3.50,
            totalLysine: 0.38,
            totalMethionine: 0.19,
            totalMetCys: 0.44,
            totalThreonine: 0.35,
            totalTryptophan: 0.12,
            totalArginine: 0.55,
            totalIsoleucine: 0.38,
            totalLeucine: 0.72,
            totalValine: 0.50,
            calcium: 0.05,
            totalPhosphorus: 0.34,
            availablePhosphorus: 0.11,
            sodium: 0.01,
            potassium: 0.45,
            chloride: 0.07,
            minPercent: 0,
            maxPercent: 40,
            pricePerKg: 100
        ),

        // ==================== PLANT BY-PRODUCTS ====================
        IngredientData(
            name: "Soybean Meal",
            group: .plantByProducts,
            dryMatter: 88.0,
            crudeProtein: 44.0,
            etherExtract: 1.50,
            crudeFiber: 7.00,
            ash: 6.30,
            starch: 10.0,
            sugar: 7.50,
            totalLysine: 2.85,
            totalMethionine: 0.62,
            totalMetCys: 1.27,
            totalThreonine: 1.75,
            totalTryptophan: 0.63,
            totalArginine: 3.25,
            totalIsoleucine: 2.00,
            totalLeucine: 3.35,
            totalValine: 2.10,
            calcium: 0.30,
            totalPhosphorus: 0.65,
            availablePhosphorus: 0.22,
            sodium: 0.02,
            potassium: 2.10,
            chloride: 0.05,
            minPercent: 0,
            maxPercent: 40,
            pricePerKg: 100
        ),

        IngredientData(
            name: "Sunflower Meal, partially dehulled",
            group: .plantByProducts,
            dryMatter: 90.0,
            crudeProtein: 34.0,
            etherExtract: 1.80,
            crudeFiber: 24.0,
            ash: 7.20,
            starch: 2.00,
            sugar: 3.50,
            totalLysine: 1.30,
            totalMethionine: 0.72,
            totalMetCys: 1.30,
            totalThreonine: 1.22,
            totalTryptophan: 0.42,
            totalArginine: 3.10,
            totalIsoleucine: 1.42,
            totalLeucine: 2.10,
            totalValine: 1.68,
            calcium: 0.35,
            totalPhosphorus: 1.00,
            availablePhosphorus: 0.30,
            sodium: 0.03,
            potassium: 1.00,
            chloride: 0.06,
            minPercent: 0,
            maxPercent: 10,
            pricePerKg: 100
        ),

        IngredientData(
            name: "Sunflower Meal, non-dehulled",
            group: .plantByProducts,
            dryMatter: 91.0,
            crudeProtein: 28.0,
            etherExtract: 1.50,
            crudeFiber: 28.0,
            ash: 6.80,
            starch: 1.50,
            sugar: 3.00,
            totalLysine: 1.05,
            totalMethionine: 0.58,
            totalMetCys: 1.05,
            totalThreonine: 1.00,
            totalTryptophan: 0.34,
            totalArginine: 2.50,
            totalIsoleucine: 1.15,
            totalLeucine: 1.70,
            totalValine: 1.35,
            calcium: 0.32,
            totalPhosphorus: 0.95,
            availablePhosphorus: 0.25,
            sodium: 0.03,
            potassium: 0.95,
            chloride: 0.05,
            minPercent: 0,
            maxPercent: 8,
            pricePerKg: 100
        ),

        IngredientData(
            name: "Soy Protein Concentrate (SPC)",
            group: .plantByProducts,
            dryMatter: 92.0,
            crudeProtein: 65.0,
            etherExtract: 0.50,
            crudeFiber: 3.50,
            ash: 6.50,
            starch: 3.00,
            sugar: 2.00,
            totalLysine: 4.10,
            totalMethionine: 0.90,
            totalMetCys: 1.82,
            totalThreonine: 2.50,
            totalTryptophan: 0.90,
            totalArginine: 4.65,
            totalIsoleucine: 2.85,
            totalLeucine: 4.80,
            totalValine: 3.00,
            calcium: 0.35,
            totalPhosphorus: 0.75,
            availablePhosphorus: 0.28,
            sodium: 0.02,
            potassium: 2.40,
            chloride: 0.05,
            minPercent: 0,
            maxPercent: 15,
            pricePerKg: 100
        ),

        IngredientData(
            name: "Rapeseed Meal",
            group: .plantByProducts,
            dryMatter: 88.0,
            crudeProtein: 34.0,
            etherExtract: 2.50,
            crudeFiber: 12.0,
            ash: 7.00,
            starch: 5.00,
            sugar: 8.00,
            totalLysine: 1.95,
            totalMethionine: 0.70,
            totalMetCys: 1.42,
            totalThreonine: 1.45,
            totalTryptophan: 0.42,
            totalArginine: 2.05,
            totalIsoleucine: 1.28,
            totalLeucine: 2.38,
            totalValine: 1.62,
            calcium: 0.70,
            totalPhosphorus: 1.05,
            availablePhosphorus: 0.32,
            sodium: 0.08,
            potassium: 1.15,
            chloride: 0.06,
            minPercent: 0,
            maxPercent: 12,
            pricePerKg: 100
        ),

        IngredientData(
            name: "Canola Meal",
            group: .plantByProducts,
            dryMatter: 88.0,
            crudeProtein: 36.0,
            etherExtract: 3.50,
            crudeFiber: 12.0,
            ash: 7.00,
            starch: 5.00,
            sugar: 8.00,
            totalLysine: 2.05,
            totalMethionine: 0.75,
            totalMetCys: 1.50,
            totalThreonine: 1.52,
            totalTryptophan: 0.45,
            totalArginine: 2.15,
            totalIsoleucine: 1.35,
            totalLeucine: 2.50,
            totalValine: 1.70,
            calcium: 0.65,
            totalPhosphorus: 1.10,
            availablePhosphorus: 0.35,
            sodium: 0.10,
            potassium: 1.20,
            chloride: 0.08,
            minPercent: 0,
            maxPercent: 15,
            pricePerKg: 100
        ),

        IngredientData(
            name: "Safflower Meal",
            group: .plantByProducts,
            dryMatter: 91.0,
            crudeProtein: 22.0,
            etherExtract: 1.20,
            crudeFiber: 32.0,
            ash: 5.00,
            starch: 2.00,
            sugar: 3.00,
            totalLysine: 0.75,
            totalMethionine: 0.38,
            totalMetCys: 0.72,
            totalThreonine: 0.72,
            totalTryptophan: 0.28,
            totalArginine: 2.00,
            totalIsoleucine: 0.85,
            totalLeucine: 1.35,
            totalValine: 1.10,
            calcium: 0.30,
            totalPhosphorus: 0.80,
            availablePhosphorus: 0.22,
            sodium: 0.02,
            potassium: 0.75,
            chloride: 0.04,
            minPercent: 0,
            maxPercent: 8,
            pricePerKg: 100
        ),

        IngredientData(
            name: "Cottonseed Meal, Expeller",
            group: .plantByProducts,
            dryMatter: 91.0,
            crudeProtein: 38.0,
            etherExtract: 5.50,
            crudeFiber: 13.0,
            ash: 6.50,
            starch: 3.00,
            sugar: 4.00,
            totalLysine: 1.70,
            totalMethionine: 0.58,
            totalMetCys: 1.20,
            totalThreonine: 1.25,
            totalTryptophan: 0.48,
            totalArginine: 4.30,
            totalIsoleucine: 1.28,
            totalLeucine: 2.35,
            totalValine: 1.80,
            calcium: 0.18,
            totalPhosphorus: 1.05,
            availablePhosphorus: 0.32,
            sodium: 0.03,
            potassium: 1.20,
            chloride: 0.05,
            minPercent: 0,
            maxPercent: 10,
            pricePerKg: 100
        ),

        IngredientData(
            name: "Cottonseed Meal, Solvent",
            group: .plantByProducts,
            dryMatter: 90.0,
            crudeProtein: 41.0,
            etherExtract: 1.20,
            crudeFiber: 14.0,
            ash: 6.80,
            starch: 2.50,
            sugar: 4.50,
            totalLysine: 1.82,
            totalMethionine: 0.62,
            totalMetCys: 1.28,
            totalThreonine: 1.32,
            totalTryptophan: 0.52,
            totalArginine: 4.60,
            totalIsoleucine: 1.35,
            totalLeucine: 2.48,
            totalValine: 1.92,
            calcium: 0.20,
            totalPhosphorus: 1.10,
            availablePhosphorus: 0.35,
            sodium: 0.03,
            potassium: 1.25,
            chloride: 0.05,
            minPercent: 0,
            maxPercent: 10,
            pricePerKg: 100
        ),

        IngredientData(
            name: "Sesame Seed Meal",
            group: .plantByProducts,
            dryMatter: 92.0,
            crudeProtein: 42.0,
            etherExtract: 10.0,
            crudeFiber: 6.00,
            ash: 11.0,
            starch: 2.00,
            sugar: 3.50,
            totalLysine: 1.15,
            totalMethionine: 1.20,
            totalMetCys: 1.85,
            totalThreonine: 1.52,
            totalTryptophan: 0.55,
            totalArginine: 5.20,
            totalIsoleucine: 1.55,
            totalLeucine: 2.80,
            totalValine: 1.95,
            calcium: 2.10,
            totalPhosphorus: 1.30,
            availablePhosphorus: 0.40,
            sodium: 0.05,
            potassium: 1.10,
            chloride: 0.05,
            minPercent: 0,
            maxPercent: 8,
            pricePerKg: 100
        ),

        IngredientData(
            name: "Peanut Meal",
            group: .plantByProducts,
            dryMatter: 91.0,
            crudeProtein: 45.0,
            etherExtract: 1.50,
            crudeFiber: 12.0,
            ash: 5.50,
            starch: 8.00,
            sugar: 9.00,
            totalLysine: 1.62,
            totalMethionine: 0.45,
            totalMetCys: 1.08,
            totalThreonine: 1.22,
            totalTryptophan: 0.42,
            totalArginine: 5.30,
            totalIsoleucine: 1.55,
            totalLeucine: 2.95,
            totalValine: 1.82,
            calcium: 0.15,
            totalPhosphorus: 0.60,
            availablePhosphorus: 0.18,
            sodium: 0.02,
            potassium: 1.00,
            chloride: 0.04,
            minPercent: 0,
            maxPercent: 10,
            pricePerKg: 100
        ),

        IngredientData(
            name: "Guar Meal",
            group: .plantByProducts,
            dryMatter: 90.0,
            crudeProtein: 42.0,
            etherExtract: 3.50,
            crudeFiber: 8.00,
            ash: 5.00,
            starch: 3.00,
            sugar: 4.00,
            totalLysine: 1.95,
            totalMethionine: 0.55,
            totalMetCys: 1.12,
            totalThreonine: 1.35,
            totalTryptophan: 0.50,
            totalArginine: 5.80,
            totalIsoleucine: 1.65,
            totalLeucine: 2.85,
            totalValine: 1.78,
            calcium: 0.65,
            totalPhosphorus: 0.55,
            availablePhosphorus: 0.15,
            sodium: 0.03,
            potassium: 1.20,
            chloride: 0.04,
            minPercent: 0,
            maxPercent: 8,
            pricePerKg: 100
        ),

        IngredientData(
            name: "Palm Kernel Meal",
            group: .plantByProducts,
            dryMatter: 91.0,
            crudeProtein: 16.0,
            etherExtract: 8.00,
            crudeFiber: 16.0,
            ash: 4.50,
            starch: 2.00,
            sugar: 2.50,
            totalLysine: 0.55,
            totalMethionine: 0.32,
            totalMetCys: 0.55,
            totalThreonine: 0.55,
            totalTryptophan: 0.16,
            totalArginine: 2.20,
            totalIsoleucine: 0.58,
            totalLeucine: 1.05,
            totalValine: 0.85,
            calcium: 0.30,
            totalPhosphorus: 0.62,
            availablePhosphorus: 0.18,
            sodium: 0.02,
            potassium: 0.65,
            chloride: 0.12,
            minPercent: 0,
            maxPercent: 15,
            pricePerKg: 100
        ),

        IngredientData(
            name: "Corn Gluten Meal",
            group: .plantByProducts,
            dryMatter: 90.0,
            crudeProtein: 60.0,
            etherExtract: 2.50,
            crudeFiber: 2.00,
            ash: 1.50,
            starch: 15.0,
            sugar: 1.00,
            totalLysine: 1.10,
            totalMethionine: 1.60,
            totalMetCys: 2.40,
            totalThreonine: 2.10,
            totalTryptophan: 0.30,
            totalArginine: 2.10,
            totalIsoleucine: 2.40,
            totalLeucine: 10.0,
            totalValine: 2.80,
            calcium: 0.05,
            totalPhosphorus: 0.50,
            availablePhosphorus: 0.18,
            sodium: 0.10,
            potassium: 0.15,
            chloride: 0.05,
            minPercent: 0,
            maxPercent: 5,
            pricePerKg: 100
        ),

        IngredientData(
            name: "DDGS, Corn",
            group: .plantByProducts,
            dryMatter: 89.0,
            crudeProtein: 27.0,
            etherExtract: 10.0,
            crudeFiber: 8.50,
            ash: 5.00,
            starch: 6.00,
            sugar: 3.00,
            totalLysine: 0.75,
            totalMethionine: 0.55,
            totalMetCys: 1.05,
            totalThreonine: 0.98,
            totalTryptophan: 0.22,
            totalArginine: 1.20,
            totalIsoleucine: 1.00,
            totalLeucine: 3.15,
            totalValine: 1.35,
            calcium: 0.05,
            totalPhosphorus: 0.85,
            availablePhosphorus: 0.65,
            sodium: 0.20,
            potassium: 1.10,
            chloride: 0.18,
            minPercent: 0,
            maxPercent: 15,
            pricePerKg: 100
        ),

        IngredientData(
            name: "Corn Germ Meal",
            group: .plantByProducts,
            dryMatter: 90.0,
            crudeProtein: 20.0,
            etherExtract: 2.50,
            crudeFiber: 8.00,
            ash: 4.00,
            starch: 20.0,
            sugar: 4.00,
            totalLysine: 0.85,
            totalMethionine: 0.38,
            totalMetCys: 0.72,
            totalThreonine: 0.70,
            totalTryptophan: 0.15,
            totalArginine: 1.35,
            totalIsoleucine: 0.65,
            totalLeucine: 1.55,
            totalValine: 0.95,
            calcium: 0.05,
            totalPhosphorus: 0.90,
            availablePhosphorus: 0.28,
            sodium: 0.02,
            potassium: 0.85,
            chloride: 0.05,
            minPercent: 0,
            maxPercent: 10,
            pricePerKg: 100
        ),

        IngredientData(
            name: "Corn Germ",
            group: .plantByProducts,
            dryMatter: 90.0,
            crudeProtein: 12.0,
            etherExtract: 20.0,
            crudeFiber: 4.00,
            ash: 3.50,
            starch: 15.0,
            sugar: 8.00,
            totalLysine: 0.52,
            totalMethionine: 0.25,
            totalMetCys: 0.48,
            totalThreonine: 0.45,
            totalTryptophan: 0.10,
            totalArginine: 0.85,
            totalIsoleucine: 0.42,
            totalLeucine: 1.00,
            totalValine: 0.62,
            calcium: 0.03,
            totalPhosphorus: 0.75,
            availablePhosphorus: 0.22,
            sodium: 0.01,
            potassium: 0.60,
            chloride: 0.04,
            minPercent: 0,
            maxPercent: 10,
            pricePerKg: 100
        ),

        IngredientData(
            name: "Corn Gluten Feed",
            group: .plantByProducts,
            dryMatter: 88.0,
            crudeProtein: 21.0,
            etherExtract: 3.00,
            crudeFiber: 8.00,
            ash: 7.00,
            starch: 18.0,
            sugar: 5.00,
            totalLysine: 0.62,
            totalMethionine: 0.40,
            totalMetCys: 0.78,
            totalThreonine: 0.70,
            totalTryptophan: 0.15,
            totalArginine: 0.95,
            totalIsoleucine: 0.72,
            totalLeucine: 2.10,
            totalValine: 1.00,
            calcium: 0.15,
            totalPhosphorus: 0.85,
            availablePhosphorus: 0.25,
            sodium: 0.25,
            potassium: 1.35,
            chloride: 0.20,
            minPercent: 0,
            maxPercent: 15,
            pricePerKg: 100
        ),

        IngredientData(
            name: "Corn Bran",
            group: .plantByProducts,
            dryMatter: 90.0,
            crudeProtein: 9.00,
            etherExtract: 1.00,
            crudeFiber: 10.0,
            ash: 1.50,
            starch: 35.0,
            sugar: 2.00,
            totalLysine: 0.35,
            totalMethionine: 0.15,
            totalMetCys: 0.30,
            totalThreonine: 0.32,
            totalTryptophan: 0.07,
            totalArginine: 0.45,
            totalIsoleucine: 0.30,
            totalLeucine: 0.85,
            totalValine: 0.42,
            calcium: 0.05,
            totalPhosphorus: 0.10,
            availablePhosphorus: 0.03,
            sodium: 0.01,
            potassium: 0.15,
            chloride: 0.03,
            minPercent: 0,
            maxPercent: 10,
            pricePerKg: 100
        ),

        IngredientData(
            name: "Wheat Gluten Meal",
            group: .plantByProducts,
            dryMatter: 92.0,
            crudeProtein: 80.0,
            etherExtract: 1.50,
            crudeFiber: 0.50,
            ash: 1.00,
            starch: 5.00,
            sugar: 1.50,
            totalLysine: 1.70,
            totalMethionine: 1.40,
            totalMetCys: 3.20,
            totalThreonine: 2.35,
            totalTryptophan: 0.80,
            totalArginine: 3.00,
            totalIsoleucine: 3.20,
            totalLeucine: 5.80,
            totalValine: 3.50,
            calcium: 0.10,
            totalPhosphorus: 0.30,
            availablePhosphorus: 0.10,
            sodium: 0.05,
            potassium: 0.10,
            chloride: 0.03,
            minPercent: 0,
            maxPercent: 5,
            pricePerKg: 100
        ),

        IngredientData(
            name: "Wheat Flour",
            group: .plantByProducts,
            dryMatter: 88.0,
            crudeProtein: 11.0,
            etherExtract: 1.50,
            crudeFiber: 0.50,
            ash: 0.50,
            starch: 70.0,
            sugar: 2.00,
            totalLysine: 0.30,
            totalMethionine: 0.18,
            totalMetCys: 0.42,
            totalThreonine: 0.32,
            totalTryptophan: 0.12,
            totalArginine: 0.45,
            totalIsoleucine: 0.40,
            totalLeucine: 0.75,
            totalValine: 0.48,
            calcium: 0.02,
            totalPhosphorus: 0.12,
            availablePhosphorus: 0.04,
            sodium: 0.01,
            potassium: 0.12,
            chloride: 0.02,
            minPercent: 0,
            maxPercent: 20,
            pricePerKg: 100
        ),

        IngredientData(
            name: "DDGS, Wheat",
            group: .plantByProducts,
            dryMatter: 90.0,
            crudeProtein: 32.0,
            etherExtract: 4.50,
            crudeFiber: 8.00,
            ash: 5.00,
            starch: 5.00,
            sugar: 3.50,
            totalLysine: 0.70,
            totalMethionine: 0.50,
            totalMetCys: 1.00,
            totalThreonine: 0.95,
            totalTryptophan: 0.35,
            totalArginine: 1.30,
            totalIsoleucine: 1.10,
            totalLeucine: 2.20,
            totalValine: 1.45,
            calcium: 0.10,
            totalPhosphorus: 0.90,
            availablePhosphorus: 0.70,
            sodium: 0.25,
            potassium: 1.20,
            chloride: 0.15,
            minPercent: 0,
            maxPercent: 12,
            pricePerKg: 100
        ),

        IngredientData(
            name: "Wheat Middlings",
            group: .plantByProducts,
            dryMatter: 88.0,
            crudeProtein: 16.0,
            etherExtract: 4.00,
            crudeFiber: 8.00,
            ash: 5.00,
            starch: 25.0,
            sugar: 5.50,
            totalLysine: 0.60,
            totalMethionine: 0.22,
            totalMetCys: 0.50,
            totalThreonine: 0.48,
            totalTryptophan: 0.20,
            totalArginine: 0.95,
            totalIsoleucine: 0.52,
            totalLeucine: 1.00,
            totalValine: 0.70,
            calcium: 0.12,
            totalPhosphorus: 0.95,
            availablePhosphorus: 0.30,
            sodium: 0.03,
            potassium: 1.10,
            chloride: 0.08,
            minPercent: 0,
            maxPercent: 20,
            pricePerKg: 100
        ),

        IngredientData(
            name: "Noodle Byproduct",
            group: .plantByProducts,
            dryMatter: 90.0,
            crudeProtein: 12.0,
            etherExtract: 2.00,
            crudeFiber: 1.00,
            ash: 1.50,
            starch: 65.0,
            sugar: 3.00,
            totalLysine: 0.32,
            totalMethionine: 0.18,
            totalMetCys: 0.42,
            totalThreonine: 0.35,
            totalTryptophan: 0.12,
            totalArginine: 0.48,
            totalIsoleucine: 0.42,
            totalLeucine: 0.80,
            totalValine: 0.50,
            calcium: 0.04,
            totalPhosphorus: 0.15,
            availablePhosphorus: 0.05,
            sodium: 0.80,
            potassium: 0.15,
            chloride: 1.20,
            minPercent: 0,
            maxPercent: 10,
            pricePerKg: 100
        ),

        IngredientData(
            name: "Wheat Bran",
            group: .plantByProducts,
            dryMatter: 88.0,
            crudeProtein: 15.0,
            etherExtract: 4.00,
            crudeFiber: 11.0,
            ash: 6.00,
            starch: 18.0,
            sugar: 6.00,
            totalLysine: 0.60,
            totalMethionine: 0.20,
            totalMetCys: 0.48,
            totalThreonine: 0.48,
            totalTryptophan: 0.22,
            totalArginine: 1.00,
            totalIsoleucine: 0.50,
            totalLeucine: 0.95,
            totalValine: 0.68,
            calcium: 0.13,
            totalPhosphorus: 1.15,
            availablePhosphorus: 0.35,
            sodium: 0.03,
            potassium: 1.20,
            chloride: 0.10,
            minPercent: 0,
            maxPercent: 15,
            pricePerKg: 100
        ),

        IngredientData(
            name: "Rice Bran",
            group: .plantByProducts,
            dryMatter: 90.0,
            crudeProtein: 13.0,
            etherExtract: 15.0,
            crudeFiber: 11.0,
            ash: 10.0,
            starch: 20.0,
            sugar: 3.00,
            totalLysine: 0.55,
            totalMethionine: 0.25,
            totalMetCys: 0.50,
            totalThreonine: 0.48,
            totalTryptophan: 0.15,
            totalArginine: 0.95,
            totalIsoleucine: 0.48,
            totalLeucine: 0.92,
            totalValine: 0.68,
            calcium: 0.08,
            totalPhosphorus: 1.70,
            availablePhosphorus: 0.25,
            sodium: 0.02,
            potassium: 1.50,
            chloride: 0.05,
            minPercent: 0,
            maxPercent: 10,
            pricePerKg: 100
        ),

        IngredientData(
            name: "Rice Hulls",
            group: .plantByProducts,
            dryMatter: 92.0,
            crudeProtein: 3.00,
            etherExtract: 0.80,
            crudeFiber: 40.0,
            ash: 18.0,
            starch: 0.50,
            sugar: 0.50,
            totalLysine: 0.10,
            totalMethionine: 0.05,
            totalMetCys: 0.10,
            totalThreonine: 0.10,
            totalTryptophan: 0.03,
            totalArginine: 0.15,
            totalIsoleucine: 0.10,
            totalLeucine: 0.20,
            totalValine: 0.15,
            calcium: 0.10,
            totalPhosphorus: 0.08,
            availablePhosphorus: 0.02,
            sodium: 0.01,
            potassium: 0.30,
            chloride: 0.03,
            minPercent: 0,
            maxPercent: 3,
            pricePerKg: 100
        ),

        IngredientData(
            name: "Soy Hulls",
            group: .plantByProducts,
            dryMatter: 90.0,
            crudeProtein: 12.0,
            etherExtract: 2.00,
            crudeFiber: 36.0,
            ash: 4.50,
            starch: 2.00,
            sugar: 3.00,
            totalLysine: 0.70,
            totalMethionine: 0.15,
            totalMetCys: 0.35,
            totalThreonine: 0.45,
            totalTryptophan: 0.15,
            totalArginine: 0.80,
            totalIsoleucine: 0.50,
            totalLeucine: 0.85,
            totalValine: 0.55,
            calcium: 0.55,
            totalPhosphorus: 0.18,
            availablePhosphorus: 0.05,
            sodium: 0.02,
            potassium: 1.20,
            chloride: 0.05,
            minPercent: 0,
            maxPercent: 5,
            pricePerKg: 100
        ),

        IngredientData(
            name: "Alfalfa Meal",
            group: .plantByProducts,
            dryMatter: 92.0,
            crudeProtein: 17.0,
            etherExtract: 2.50,
            crudeFiber: 25.0,
            ash: 10.0,
            starch: 3.00,
            sugar: 6.00,
            totalLysine: 0.80,
            totalMethionine: 0.28,
            totalMetCys: 0.52,
            totalThreonine: 0.70,
            totalTryptophan: 0.32,
            totalArginine: 0.85,
            totalIsoleucine: 0.78,
            totalLeucine: 1.30,
            totalValine: 0.95,
            calcium: 1.40,
            totalPhosphorus: 0.25,
            availablePhosphorus: 0.08,
            sodium: 0.10,
            potassium: 2.20,
            chloride: 0.35,
            minPercent: 0,
            maxPercent: 5,
            pricePerKg: 100
        ),

        IngredientData(
            name: "Date Palm Seeds",
            group: .plantByProducts,
            dryMatter: 92.0,
            crudeProtein: 5.50,
            etherExtract: 8.00,
            crudeFiber: 15.0,
            ash: 1.50,
            starch: 5.00,
            sugar: 45.0,
            totalLysine: 0.25,
            totalMethionine: 0.10,
            totalMetCys: 0.20,
            totalThreonine: 0.22,
            totalTryptophan: 0.05,
            totalArginine: 0.35,
            totalIsoleucine: 0.22,
            totalLeucine: 0.42,
            totalValine: 0.30,
            calcium: 0.08,
            totalPhosphorus: 0.10,
            availablePhosphorus: 0.03,
            sodium: 0.02,
            potassium: 0.55,
            chloride: 0.08,
            minPercent: 0,
            maxPercent: 10,
            pricePerKg: 100
        ),

        IngredientData(
            name: "Molasses, Beet",
            group: .plantByProducts,
            dryMatter: 78.0,
            crudeProtein: 8.00,
            etherExtract: 0.20,
            crudeFiber: 0.00,
            ash: 10.0,
            starch: 0.00,
            sugar: 50.0,
            totalLysine: 0.05,
            totalMethionine: 0.02,
            totalMetCys: 0.08,
            totalThreonine: 0.20,
            totalTryptophan: 0.02,
            totalArginine: 0.10,
            totalIsoleucine: 0.08,
            totalLeucine: 0.10,
            totalValine: 0.12,
            calcium: 0.20,
            totalPhosphorus: 0.05,
            availablePhosphorus: 0.03,
            sodium: 1.00,
            potassium: 4.50,
            chloride: 1.00,
            minPercent: 0,
            maxPercent: 5,
            pricePerKg: 100
        ),

        IngredientData(
            name: "Molasses, Sugarcane",
            group: .plantByProducts,
            dryMatter: 75.0,
            crudeProtein: 4.00,
            etherExtract: 0.10,
            crudeFiber: 0.00,
            ash: 8.00,
            starch: 0.00,
            sugar: 55.0,
            totalLysine: 0.02,
            totalMethionine: 0.01,
            totalMetCys: 0.04,
            totalThreonine: 0.10,
            totalTryptophan: 0.01,
            totalArginine: 0.05,
            totalIsoleucine: 0.04,
            totalLeucine: 0.05,
            totalValine: 0.06,
            calcium: 0.80,
            totalPhosphorus: 0.08,
            availablePhosphorus: 0.05,
            sodium: 0.20,
            potassium: 3.50,
            chloride: 1.50,
            minPercent: 0,
            maxPercent: 5,
            pricePerKg: 100
        ),

        // ==================== ANIMAL SOURCES ====================
        IngredientData(
            name: "Fish Meal 65%",
            group: .animalSource,
            dryMatter: 92.0,
            crudeProtein: 65.0,
            etherExtract: 9.00,
            crudeFiber: 0.50,
            ash: 16.0,
            starch: 0.00,
            sugar: 0.00,
            totalLysine: 5.12,
            totalMethionine: 1.95,
            totalMetCys: 2.80,
            totalThreonine: 2.88,
            totalTryptophan: 0.72,
            totalArginine: 3.80,
            totalIsoleucine: 2.95,
            totalLeucine: 5.00,
            totalValine: 3.42,
            calcium: 4.50,
            totalPhosphorus: 2.90,
            availablePhosphorus: 2.00,
            sodium: 0.85,
            potassium: 0.95,
            chloride: 0.30,
            minPercent: 0,
            maxPercent: 5,
            pricePerKg: 100
        ),

        IngredientData(
            name: "Meat and Bone Meal",
            group: .animalSource,
            dryMatter: 93.0,
            crudeProtein: 50.0,
            etherExtract: 10.0,
            crudeFiber: 2.50,
            ash: 28.0,
            starch: 0.00,
            sugar: 0.00,
            totalLysine: 2.60,
            totalMethionine: 0.75,
            totalMetCys: 1.20,
            totalThreonine: 1.80,
            totalTryptophan: 0.35,
            totalArginine: 3.70,
            totalIsoleucine: 1.40,
            totalLeucine: 3.20,
            totalValine: 2.10,
            calcium: 10.0,
            totalPhosphorus: 5.00,
            availablePhosphorus: 2.50,
            sodium: 0.65,
            potassium: 0.50,
            chloride: 0.25,
            minPercent: 0,
            maxPercent: 5,
            pricePerKg: 100
        ),

        IngredientData(
            name: "Poultry By-Product Meal",
            group: .animalSource,
            dryMatter: 93.0,
            crudeProtein: 60.0,
            etherExtract: 13.0,
            crudeFiber: 2.00,
            ash: 14.0,
            starch: 0.00,
            sugar: 0.00,
            totalLysine: 3.20,
            totalMethionine: 1.10,
            totalMetCys: 1.80,
            totalThreonine: 2.20,
            totalTryptophan: 0.45,
            totalArginine: 4.00,
            totalIsoleucine: 2.10,
            totalLeucine: 3.90,
            totalValine: 2.60,
            calcium: 4.00,
            totalPhosphorus: 2.20,
            availablePhosphorus: 1.20,
            sodium: 0.40,
            potassium: 0.60,
            chloride: 0.20,
            minPercent: 0,
            maxPercent: 8,
            pricePerKg: 100
        ),

        // ==================== FATS & OILS ====================
        IngredientData(
            name: "Oil",
            group: .fat,
            dryMatter: 99.5,
            crudeProtein: 0.00,
            etherExtract: 99.0,
            crudeFiber: 0.00,
            ash: 0.00,
            starch: 0.00,
            sugar: 0.00,
            totalLysine: 0.00,
            totalMethionine: 0.00,
            totalMetCys: 0.00,
            totalThreonine: 0.00,
            totalTryptophan: 0.00,
            totalArginine: 0.00,
            totalIsoleucine: 0.00,
            totalLeucine: 0.00,
            totalValine: 0.00,
            calcium: 0.00,
            totalPhosphorus: 0.00,
            availablePhosphorus: 0.00,
            sodium: 0.00,
            potassium: 0.00,
            chloride: 0.00,
            minPercent: 0,
            maxPercent: 6,
            pricePerKg: 100
        ),

        IngredientData(
            name: "Fat, Crystalline",
            group: .fat,
            dryMatter: 99.5,
            crudeProtein: 0.00,
            etherExtract: 99.0,
            crudeFiber: 0.00,
            ash: 0.00,
            starch: 0.00,
            sugar: 0.00,
            totalLysine: 0.00,
            totalMethionine: 0.00,
            totalMetCys: 0.00,
            totalThreonine: 0.00,
            totalTryptophan: 0.00,
            totalArginine: 0.00,
            totalIsoleucine: 0.00,
            totalLeucine: 0.00,
            totalValine: 0.00,
            calcium: 0.00,
            totalPhosphorus: 0.00,
            availablePhosphorus: 0.00,
            sodium: 0.00,
            potassium: 0.00,
            chloride: 0.00,
            minPercent: 0,
            maxPercent: 5,
            pricePerKg: 100
        ),

        IngredientData(
            name: "Fat, Calcium Salt",
            group: .fat,
            dryMatter: 97.0,
            crudeProtein: 0.00,
            etherExtract: 84.0,
            crudeFiber: 0.00,
            ash: 13.0,
            starch: 0.00,
            sugar: 0.00,
            totalLysine: 0.00,
            totalMethionine: 0.00,
            totalMetCys: 0.00,
            totalThreonine: 0.00,
            totalTryptophan: 0.00,
            totalArginine: 0.00,
            totalIsoleucine: 0.00,
            totalLeucine: 0.00,
            totalValine: 0.00,
            calcium: 9.00,
            totalPhosphorus: 0.00,
            availablePhosphorus: 0.00,
            sodium: 0.00,
            potassium: 0.00,
            chloride: 0.00,
            minPercent: 0,
            maxPercent: 5,
            pricePerKg: 100
        ),

        // ==================== SUPP & ADDITIVES - AMINO ACIDS ====================
        IngredientData(
            name: "DL-Methionine",
            group: .supplementsAdditives,
            dryMatter: 99.0,
            crudeProtein: 58.1,
            etherExtract: 0.00,
            crudeFiber: 0.00,
            ash: 0.10,
            starch: 0.00,
            sugar: 0.00,
            totalLysine: 0.00,
            totalMethionine: 99.0,
            totalMetCys: 99.0,
            totalThreonine: 0.00,
            totalTryptophan: 0.00,
            totalArginine: 0.00,
            totalIsoleucine: 0.00,
            totalLeucine: 0.00,
            totalValine: 0.00,
            calcium: 0.00,
            totalPhosphorus: 0.00,
            availablePhosphorus: 0.00,
            sodium: 0.00,
            potassium: 0.00,
            chloride: 0.00,
            minPercent: 0,
            maxPercent: 0.50,
            pricePerKg: 100
        ),

        IngredientData(
            name: "L-Lysine-HCl",
            group: .supplementsAdditives,
            dryMatter: 99.0,
            crudeProtein: 93.4,
            etherExtract: 0.00,
            crudeFiber: 0.00,
            ash: 0.50,
            starch: 0.00,
            sugar: 0.00,
            totalLysine: 78.0,
            totalMethionine: 0.00,
            totalMetCys: 0.00,
            totalThreonine: 0.00,
            totalTryptophan: 0.00,
            totalArginine: 0.00,
            totalIsoleucine: 0.00,
            totalLeucine: 0.00,
            totalValine: 0.00,
            calcium: 0.00,
            totalPhosphorus: 0.00,
            availablePhosphorus: 0.00,
            sodium: 0.00,
            potassium: 0.00,
            chloride: 19.5,
            minPercent: 0,
            maxPercent: 0.60,
            pricePerKg: 100
        ),

        IngredientData(
            name: "L-Lysine-Sulfate",
            group: .supplementsAdditives,
            dryMatter: 99.0,
            crudeProtein: 80.0,
            etherExtract: 0.00,
            crudeFiber: 0.00,
            ash: 15.0,
            starch: 0.00,
            sugar: 0.00,
            totalLysine: 51.0,
            totalMethionine: 0.00,
            totalMetCys: 0.00,
            totalThreonine: 0.00,
            totalTryptophan: 0.00,
            totalArginine: 0.00,
            totalIsoleucine: 0.00,
            totalLeucine: 0.00,
            totalValine: 0.00,
            calcium: 0.00,
            totalPhosphorus: 0.00,
            availablePhosphorus: 0.00,
            sodium: 0.00,
            potassium: 0.00,
            chloride: 0.00,
            minPercent: 0,
            maxPercent: 0.80,
            pricePerKg: 100
        ),

        IngredientData(
            name: "L-Threonine",
            group: .supplementsAdditives,
            dryMatter: 99.0,
            crudeProtein: 73.5,
            etherExtract: 0.00,
            crudeFiber: 0.00,
            ash: 0.20,
            starch: 0.00,
            sugar: 0.00,
            totalLysine: 0.00,
            totalMethionine: 0.00,
            totalMetCys: 0.00,
            totalThreonine: 98.5,
            totalTryptophan: 0.00,
            totalArginine: 0.00,
            totalIsoleucine: 0.00,
            totalLeucine: 0.00,
            totalValine: 0.00,
            calcium: 0.00,
            totalPhosphorus: 0.00,
            availablePhosphorus: 0.00,
            sodium: 0.00,
            potassium: 0.00,
            chloride: 0.00,
            minPercent: 0,
            maxPercent: 0.30,
            pricePerKg: 100
        ),

        IngredientData(
            name: "L-Tryptophan",
            group: .supplementsAdditives,
            dryMatter: 99.0,
            crudeProtein: 98.0,
            etherExtract: 0.00,
            crudeFiber: 0.00,
            ash: 0.10,
            starch: 0.00,
            sugar: 0.00,
            totalLysine: 0.00,
            totalMethionine: 0.00,
            totalMetCys: 0.00,
            totalThreonine: 0.00,
            totalTryptophan: 98.0,
            totalArginine: 0.00,
            totalIsoleucine: 0.00,
            totalLeucine: 0.00,
            totalValine: 0.00,
            calcium: 0.00,
            totalPhosphorus: 0.00,
            availablePhosphorus: 0.00,
            sodium: 0.00,
            potassium: 0.00,
            chloride: 0.00,
            minPercent: 0,
            maxPercent: 0.10,
            pricePerKg: 100
        ),

        IngredientData(
            name: "L-Valine",
            group: .supplementsAdditives,
            dryMatter: 99.0,
            crudeProtein: 98.0,
            etherExtract: 0.00,
            crudeFiber: 0.00,
            ash: 0.10,
            starch: 0.00,
            sugar: 0.00,
            totalLysine: 0.00,
            totalMethionine: 0.00,
            totalMetCys: 0.00,
            totalThreonine: 0.00,
            totalTryptophan: 0.00,
            totalArginine: 0.00,
            totalIsoleucine: 0.00,
            totalLeucine: 0.00,
            totalValine: 98.0,
            calcium: 0.00,
            totalPhosphorus: 0.00,
            availablePhosphorus: 0.00,
            sodium: 0.00,
            potassium: 0.00,
            chloride: 0.00,
            minPercent: 0,
            maxPercent: 0.20,
            pricePerKg: 100
        ),

        IngredientData(
            name: "L-Isoleucine",
            group: .supplementsAdditives,
            dryMatter: 99.0,
            crudeProtein: 98.0,
            etherExtract: 0.00,
            crudeFiber: 0.00,
            ash: 0.10,
            starch: 0.00,
            sugar: 0.00,
            totalLysine: 0.00,
            totalMethionine: 0.00,
            totalMetCys: 0.00,
            totalThreonine: 0.00,
            totalTryptophan: 0.00,
            totalArginine: 0.00,
            totalIsoleucine: 98.0,
            totalLeucine: 0.00,
            totalValine: 0.00,
            calcium: 0.00,
            totalPhosphorus: 0.00,
            availablePhosphorus: 0.00,
            sodium: 0.00,
            potassium: 0.00,
            chloride: 0.00,
            minPercent: 0,
            maxPercent: 0.20,
            pricePerKg: 100
        ),

        IngredientData(
            name: "L-Arginine",
            group: .supplementsAdditives,
            dryMatter: 99.0,
            crudeProtein: 98.0,
            etherExtract: 0.00,
            crudeFiber: 0.00,
            ash: 0.10,
            starch: 0.00,
            sugar: 0.00,
            totalLysine: 0.00,
            totalMethionine: 0.00,
            totalMetCys: 0.00,
            totalThreonine: 0.00,
            totalTryptophan: 0.00,
            totalArginine: 98.0,
            totalIsoleucine: 0.00,
            totalLeucine: 0.00,
            totalValine: 0.00,
            calcium: 0.00,
            totalPhosphorus: 0.00,
            availablePhosphorus: 0.00,
            sodium: 0.00,
            potassium: 0.00,
            chloride: 0.00,
            minPercent: 0,
            maxPercent: 0.30,
            pricePerKg: 100
        ),

        // ==================== SUPP & ADDITIVES - MINERALS ====================
        IngredientData(
            name: "Di Calcium Phosphate",
            group: .supplementsAdditives,
            dryMatter: 98.0,
            crudeProtein: 0.00,
            etherExtract: 0.00,
            crudeFiber: 0.00,
            ash: 98.0,
            starch: 0.00,
            sugar: 0.00,
            totalLysine: 0.00,
            totalMethionine: 0.00,
            totalMetCys: 0.00,
            totalThreonine: 0.00,
            totalTryptophan: 0.00,
            totalArginine: 0.00,
            totalIsoleucine: 0.00,
            totalLeucine: 0.00,
            totalValine: 0.00,
            calcium: 23.0,
            totalPhosphorus: 18.5,
            availablePhosphorus: 18.0,
            sodium: 0.00,
            potassium: 0.00,
            chloride: 0.00,
            minPercent: 0,
            maxPercent: 2.50,
            pricePerKg: 100
        ),

        IngredientData(
            name: "Mono Calcium Phosphate",
            group: .supplementsAdditives,
            dryMatter: 98.0,
            crudeProtein: 0.00,
            etherExtract: 0.00,
            crudeFiber: 0.00,
            ash: 98.0,
            starch: 0.00,
            sugar: 0.00,
            totalLysine: 0.00,
            totalMethionine: 0.00,
            totalMetCys: 0.00,
            totalThreonine: 0.00,
            totalTryptophan: 0.00,
            totalArginine: 0.00,
            totalIsoleucine: 0.00,
            totalLeucine: 0.00,
            totalValine: 0.00,
            calcium: 16.0,
            totalPhosphorus: 22.0,
            availablePhosphorus: 21.5,
            sodium: 0.00,
            potassium: 0.00,
            chloride: 0.00,
            minPercent: 0,
            maxPercent: 2.00,
            pricePerKg: 100
        ),

        IngredientData(
            name: "Calcium Carbonate",
            group: .supplementsAdditives,
            dryMatter: 99.0,
            crudeProtein: 0.00,
            etherExtract: 0.00,
            crudeFiber: 0.00,
            ash: 99.0,
            starch: 0.00,
            sugar: 0.00,
            totalLysine: 0.00,
            totalMethionine: 0.00,
            totalMetCys: 0.00,
            totalThreonine: 0.00,
            totalTryptophan: 0.00,
            totalArginine: 0.00,
            totalIsoleucine: 0.00,
            totalLeucine: 0.00,
            totalValine: 0.00,
            calcium: 38.0,
            totalPhosphorus: 0.00,
            availablePhosphorus: 0.00,
            sodium: 0.00,
            potassium: 0.00,
            chloride: 0.00,
            minPercent: 0,
            maxPercent: 3.00,
            pricePerKg: 100
        ),

        IngredientData(
            name: "Limestone",
            group: .supplementsAdditives,
            dryMatter: 99.0,
            crudeProtein: 0.00,
            etherExtract: 0.00,
            crudeFiber: 0.00,
            ash: 99.0,
            starch: 0.00,
            sugar: 0.00,
            totalLysine: 0.00,
            totalMethionine: 0.00,
            totalMetCys: 0.00,
            totalThreonine: 0.00,
            totalTryptophan: 0.00,
            totalArginine: 0.00,
            totalIsoleucine: 0.00,
            totalLeucine: 0.00,
            totalValine: 0.00,
            calcium: 38.0,
            totalPhosphorus: 0.00,
            availablePhosphorus: 0.00,
            sodium: 0.00,
            potassium: 0.00,
            chloride: 0.00,
            minPercent: 0,
            maxPercent: 3.00,
            pricePerKg: 100
        ),

        IngredientData(
            name: "Na-Bicarbonate (Soda)",
            group: .supplementsAdditives,
            dryMatter: 99.0,
            crudeProtein: 0.00,
            etherExtract: 0.00,
            crudeFiber: 0.00,
            ash: 99.0,
            starch: 0.00,
            sugar: 0.00,
            totalLysine: 0.00,
            totalMethionine: 0.00,
            totalMetCys: 0.00,
            totalThreonine: 0.00,
            totalTryptophan: 0.00,
            totalArginine: 0.00,
            totalIsoleucine: 0.00,
            totalLeucine: 0.00,
            totalValine: 0.00,
            calcium: 0.00,
            totalPhosphorus: 0.00,
            availablePhosphorus: 0.00,
            sodium: 27.0,
            potassium: 0.00,
            chloride: 0.00,
            minPercent: 0,
            maxPercent: 0.50,
            pricePerKg: 100
        ),

        IngredientData(
            name: "Potassium Carbonate",
            group: .supplementsAdditives,
            dryMatter: 99.0,
            crudeProtein: 0.00,
            etherExtract: 0.00,
            crudeFiber: 0.00,
            ash: 99.0,
            starch: 0.00,
            sugar: 0.00,
            totalLysine: 0.00,
            totalMethionine: 0.00,
            totalMetCys: 0.00,
            totalThreonine: 0.00,
            totalTryptophan: 0.00,
            totalArginine: 0.00,
            totalIsoleucine: 0.00,
            totalLeucine: 0.00,
            totalValine: 0.00,
            calcium: 0.00,
            totalPhosphorus: 0.00,
            availablePhosphorus: 0.00,
            sodium: 0.00,
            potassium: 56.5,
            chloride: 0.00,
            minPercent: 0,
            maxPercent: 0.30,
            pricePerKg: 100
        ),

        IngredientData(
            name: "NaCl (Salt)",
            group: .supplementsAdditives,
            dryMatter: 99.5,
            crudeProtein: 0.00,
            etherExtract: 0.00,
            crudeFiber: 0.00,
            ash: 99.5,
            starch: 0.00,
            sugar: 0.00,
            totalLysine: 0.00,
            totalMethionine: 0.00,
            totalMetCys: 0.00,
            totalThreonine: 0.00,
            totalTryptophan: 0.00,
            totalArginine: 0.00,
            totalIsoleucine: 0.00,
            totalLeucine: 0.00,
            totalValine: 0.00,
            calcium: 0.00,
            totalPhosphorus: 0.00,
            availablePhosphorus: 0.00,
            sodium: 39.0,
            potassium: 0.00,
            chloride: 60.0,
            minPercent: 0,
            maxPercent: 0.50,
            pricePerKg: 100
        ),

        IngredientData(
            name: "Potassium Chloride",
            group: .supplementsAdditives,
            dryMatter: 99.0,
            crudeProtein: 0.00,
            etherExtract: 0.00,
            crudeFiber: 0.00,
            ash: 99.0,
            starch: 0.00,
            sugar: 0.00,
            totalLysine: 0.00,
            totalMethionine: 0.00,
            totalMetCys: 0.00,
            totalThreonine: 0.00,
            totalTryptophan: 0.00,
            totalArginine: 0.00,
            totalIsoleucine: 0.00,
            totalLeucine: 0.00,
            totalValine: 0.00,
            calcium: 0.00,
            totalPhosphorus: 0.00,
            availablePhosphorus: 0.00,
            sodium: 0.00,
            potassium: 52.0,
            chloride: 47.0,
            minPercent: 0,
            maxPercent: 0.30,
            pricePerKg: 100
        ),

        IngredientData(
            name: "Ammonium Chloride",
            group: .supplementsAdditives,
            dryMatter: 99.0,
            crudeProtein: 0.00,
            etherExtract: 0.00,
            crudeFiber: 0.00,
            ash: 99.0,
            starch: 0.00,
            sugar: 0.00,
            totalLysine: 0.00,
            totalMethionine: 0.00,
            totalMetCys: 0.00,
            totalThreonine: 0.00,
            totalTryptophan: 0.00,
            totalArginine: 0.00,
            totalIsoleucine: 0.00,
            totalLeucine: 0.00,
            totalValine: 0.00,
            calcium: 0.00,
            totalPhosphorus: 0.00,
            availablePhosphorus: 0.00,
            sodium: 0.00,
            potassium: 0.00,
            chloride: 66.0,
            minPercent: 0,
            maxPercent: 0.20,
            pricePerKg: 100
        ),

        IngredientData(
            name: "Choline Chloride",
            group: .supplementsAdditives,
            dryMatter: 98.0,
            crudeProtein: 0.00,
            etherExtract: 0.00,
            crudeFiber: 0.00,
            ash: 5.00,
            starch: 0.00,
            sugar: 0.00,
            totalLysine: 0.00,
            totalMethionine: 0.00,
            totalMetCys: 0.00,
            totalThreonine: 0.00,
            totalTryptophan: 0.00,
            totalArginine: 0.00,
            totalIsoleucine: 0.00,
            totalLeucine: 0.00,
            totalValine: 0.00,
            calcium: 0.00,
            totalPhosphorus: 0.00,
            availablePhosphorus: 0.00,
            sodium: 0.00,
            potassium: 0.00,
            chloride: 25.0,
            minPercent: 0,
            maxPercent: 0.20,
            pricePerKg: 100
        ),

        IngredientData(
            name: "Vit-Min Premix",
            group: .supplementsAdditives,
            dryMatter: 98.0,
            crudeProtein: 0.00,
            etherExtract: 0.00,
            crudeFiber: 0.00,
            ash: 50.0,
            starch: 0.00,
            sugar: 0.00,
            totalLysine: 0.00,
            totalMethionine: 0.00,
            totalMetCys: 0.00,
            totalThreonine: 0.00,
            totalTryptophan: 0.00,
            totalArginine: 0.00,
            totalIsoleucine: 0.00,
            totalLeucine: 0.00,
            totalValine: 0.00,
            calcium: 10.0,
            totalPhosphorus: 2.00,
            availablePhosphorus: 0.50,
            sodium: 2.00,
            potassium: 1.00,
            chloride: 1.00,
            minPercent: 0.05,
            maxPercent: 0.50,
            pricePerKg: 100
        ),

        IngredientData(
            name: "Bentonite",
            group: .supplementsAdditives,
            dryMatter: 92.0,
            crudeProtein: 0.00,
            etherExtract: 0.00,
            crudeFiber: 0.00,
            ash: 90.0,
            starch: 0.00,
            sugar: 0.00,
            totalLysine: 0.00,
            totalMethionine: 0.00,
            totalMetCys: 0.00,
            totalThreonine: 0.00,
            totalTryptophan: 0.00,
            totalArginine: 0.00,
            totalIsoleucine: 0.00,
            totalLeucine: 0.00,
            totalValine: 0.00,
            calcium: 1.50,
            totalPhosphorus: 0.05,
            availablePhosphorus: 0.00,
            sodium: 2.50,
            potassium: 0.50,
            chloride: 0.10,
            minPercent: 0,
            maxPercent: 2.00,
            pricePerKg: 100
        ),

        IngredientData(
            name: "Toxin Binder",
            group: .supplementsAdditives,
            dryMatter: 95.0,
            crudeProtein: 0.00,
            etherExtract: 0.00,
            crudeFiber: 0.00,
            ash: 90.0,
            starch: 0.00,
            sugar: 0.00,
            totalLysine: 0.00,
            totalMethionine: 0.00,
            totalMetCys: 0.00,
            totalThreonine: 0.00,
            totalTryptophan: 0.00,
            totalArginine: 0.00,
            totalIsoleucine: 0.00,
            totalLeucine: 0.00,
            totalValine: 0.00,
            calcium: 2.00,
            totalPhosphorus: 0.05,
            availablePhosphorus: 0.00,
            sodium: 1.00,
            potassium: 0.30,
            chloride: 0.05,
            minPercent: 0,
            maxPercent: 0.50,
            pricePerKg: 100
        ),

        IngredientData(
            name: "Phytase",
            group: .supplementsAdditives,
            dryMatter: 98.0,
            crudeProtein: 0.00,
            etherExtract: 0.00,
            crudeFiber: 0.00,
            ash: 20.0,
            starch: 0.00,
            sugar: 0.00,
            totalLysine: 0.00,
            totalMethionine: 0.00,
            totalMetCys: 0.00,
            totalThreonine: 0.00,
            totalTryptophan: 0.00,
            totalArginine: 0.00,
            totalIsoleucine: 0.00,
            totalLeucine: 0.00,
            totalValine: 0.00,
            calcium: 2.00,
            totalPhosphorus: 1.00,
            availablePhosphorus: 0.00,
            sodium: 0.50,
            potassium: 0.30,
            chloride: 0.20,
            minPercent: 0.00,
            maxPercent: 0.05,
            pricePerKg: 100
        ),

        IngredientData(
            name: "Probiotic",
            group: .supplementsAdditives,
            dryMatter: 95.0,
            crudeProtein: 5.00,
            etherExtract: 1.00,
            crudeFiber: 0.00,
            ash: 10.0,
            starch: 0.00,
            sugar: 0.00,
            totalLysine: 0.00,
            totalMethionine: 0.00,
            totalMetCys: 0.00,
            totalThreonine: 0.00,
            totalTryptophan: 0.00,
            totalArginine: 0.00,
            totalIsoleucine: 0.00,
            totalLeucine: 0.00,
            totalValine: 0.00,
            calcium: 1.00,
            totalPhosphorus: 0.50,
            availablePhosphorus: 0.20,
            sodium: 0.50,
            potassium: 0.30,
            chloride: 0.10,
            minPercent: 0,
            maxPercent: 0.20,
            pricePerKg: 100
        ),

        IngredientData(
            name: "Acidifier",
            group: .supplementsAdditives,
            dryMatter: 98.0,
            crudeProtein: 0.00,
            etherExtract: 0.00,
            crudeFiber: 0.00,
            ash: 5.00,
            starch: 0.00,
            sugar: 0.00,
            totalLysine: 0.00,
            totalMethionine: 0.00,
            totalMetCys: 0.00,
            totalThreonine: 0.00,
            totalTryptophan: 0.00,
            totalArginine: 0.00,
            totalIsoleucine: 0.00,
            totalLeucine: 0.00,
            totalValine: 0.00,
            calcium: 0.00,
            totalPhosphorus: 0.00,
            availablePhosphorus: 0.00,
            sodium: 0.00,
            potassium: 0.00,
            chloride: 0.00,
            minPercent: 0,
            maxPercent: 0.30,
            pricePerKg: 100
        ),

        IngredientData(
            name: "Filler",
            group: .supplementsAdditives,
            dryMatter: 90.0,
            crudeProtein: 0.00,
            etherExtract: 0.00,
            crudeFiber: 0.00,
            ash: 90.0,
            starch: 0.00,
            sugar: 0.00,
            totalLysine: 0.00,
            totalMethionine: 0.00,
            totalMetCys: 0.00,
            totalThreonine: 0.00,
            totalTryptophan: 0.00,
            totalArginine: 0.00,
            totalIsoleucine: 0.00,
            totalLeucine: 0.00,
            totalValine: 0.00,
            calcium: 0.50,
            totalPhosphorus: 0.05,
            availablePhosphorus: 0.00,
            sodium: 0.10,
            potassium: 0.10,
            chloride: 0.05,
            minPercent: 0,
            maxPercent: 2.00,
            pricePerKg: 100
        )
    ]

    /// Calculate WPSA-based AME for an ingredient
    static func calculateWPSAAME(for ingredient: IngredientData) -> Double {
        let nfe = max(0, ingredient.dryMatter - ingredient.crudeProtein - ingredient.etherExtract - ingredient.crudeFiber - ingredient.ash)

        let energyKJ = (ingredient.crudeProtein * wpsaCoefficients.crudeProtein +
                        ingredient.etherExtract * wpsaCoefficients.etherExtract +
                        nfe * wpsaCoefficients.nfe +
                        ingredient.starch * 0.95 * wpsaCoefficients.starch +
                        ingredient.sugar * 0.95 * wpsaCoefficients.sugar) / 100.0

        return energyKJ * wpsaCoefficients.conversionFactor * 10.0 // kJ/g to kcal/kg
    }

    /// Calculate SID amino acid value for an ingredient
    static func calculateSIDAminoAcid(ingredientName: String, aminoAcid: String, totalValue: Double) -> Double {
        guard let coefficients = sidDigestibility[ingredientName],
              let digestibility = coefficients[aminoAcid] else {
            // Default digestibility if not found (conservative estimate)
            return totalValue * 0.85
        }
        return totalValue * digestibility
    }
}

/// Extended ingredient data structure with all nutrients from Excel
struct IngredientData: Identifiable {
    let id = UUID()
    let name: String
    let group: IngredientGroup

    // Proximate analysis
    let dryMatter: Double
    let crudeProtein: Double
    let etherExtract: Double
    let crudeFiber: Double
    let ash: Double
    let starch: Double
    let sugar: Double

    // Total amino acids (before SID adjustment)
    let totalLysine: Double
    let totalMethionine: Double
    let totalMetCys: Double
    let totalThreonine: Double
    let totalTryptophan: Double
    let totalArginine: Double
    let totalIsoleucine: Double
    let totalLeucine: Double
    let totalValine: Double

    // Minerals
    let calcium: Double
    let totalPhosphorus: Double
    let availablePhosphorus: Double
    let sodium: Double
    let potassium: Double
    let chloride: Double

    // Constraints
    var minPercent: Double
    var maxPercent: Double
    var pricePerKg: Double

    // Computed properties
    var nfe: Double {
        max(0, dryMatter - crudeProtein - etherExtract - crudeFiber - ash)
    }

    var ame: Double {
        IngredientDatabase.calculateWPSAAME(for: self)
    }

    var sidLysine: Double {
        IngredientDatabase.calculateSIDAminoAcid(ingredientName: name, aminoAcid: "lysine", totalValue: totalLysine)
    }

    var sidMethionine: Double {
        IngredientDatabase.calculateSIDAminoAcid(ingredientName: name, aminoAcid: "methionine", totalValue: totalMethionine)
    }

    var sidMetCys: Double {
        IngredientDatabase.calculateSIDAminoAcid(ingredientName: name, aminoAcid: "metCys", totalValue: totalMetCys)
    }

    var sidThreonine: Double {
        IngredientDatabase.calculateSIDAminoAcid(ingredientName: name, aminoAcid: "threonine", totalValue: totalThreonine)
    }

    var sidTryptophan: Double {
        IngredientDatabase.calculateSIDAminoAcid(ingredientName: name, aminoAcid: "tryptophan", totalValue: totalTryptophan)
    }

    var sidArginine: Double {
        IngredientDatabase.calculateSIDAminoAcid(ingredientName: name, aminoAcid: "arginine", totalValue: totalArginine)
    }

    var sidIsoleucine: Double {
        IngredientDatabase.calculateSIDAminoAcid(ingredientName: name, aminoAcid: "isoleucine", totalValue: totalIsoleucine)
    }

    var sidLeucine: Double {
        IngredientDatabase.calculateSIDAminoAcid(ingredientName: name, aminoAcid: "leucine", totalValue: totalLeucine)
    }

    var sidValine: Double {
        IngredientDatabase.calculateSIDAminoAcid(ingredientName: name, aminoAcid: "valine", totalValue: totalValine)
    }
}

/// WPSA energy calculation coefficients
struct WPSACoefficients {
    let crudeProtein: Double
    let etherExtract: Double
    let nfe: Double
    let crudeFiber: Double
    let ash: Double
    let starch: Double
    let sugar: Double
    let conversionFactor: Double // kJ to kcal
}
